### ISSUE TITLE
Publish Public docker image to use with gitlab CI

### ISSUE THREAD

**Issue by darkradish** [grafana/xk6-output-influxdb#11]
Hello,

Can you publish a public image to use it directly with gitlab ci instead of loadimpact/k6 ?

Regards

**Comment by javaducky** [comment]
Hi @darkradish. We haven't been publishing k6 images with extensions because k6 can be extended with multiple extensions. We'd end up having to create so many permutations of images having varying extensions included, so it's easier to just have folks build their own custom image containing all the features they want. We've been including the `Dockerfile` locally to ease the process of creating your own custom image which could then be pushed to your container registry.

I'm planning to discuss this internally if we want to start pushing images with just this extension. Obviously, anyone wishing to include an additional extension would have the same issue in that they'd have to build the image on their own.

Also, if you're using the `loadimpact/k6` image, please switch to `grafana/k6` as we are now part of Grafana Labs.

**Comment by javaducky** [comment]
Closing issue given discussion. We don't wish to maintain the images at this time. Recommend creating and pushing an image specific to your needs into whichever container registry you use.

**Comment by henri9813** [comment]
Hello,

Does this change in 2026 ?
